/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'image' : ExternalBlob,
});
export const Review = IDL.Record({
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
  'reviewer' : IDL.Principal,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'ratings' : IDL.Vec(Review),
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'vendor' : IDL.Principal,
  'discount' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const OutletStatus = IDL.Variant({
  'disabled' : IDL.Null,
  'enabled' : IDL.Null,
});
export const Vendor = IDL.Record({
  'principal' : IDL.Principal,
  'verified' : IDL.Bool,
  'outletStatus' : OutletStatus,
  'name' : IDL.Text,
  'outletName' : IDL.Text,
  'walletDue' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'customer' : IDL.Principal,
  'vendor' : IDL.Principal,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const VendorDashboardStats = IDL.Record({
  'totalSalesAmount' : IDL.Nat,
  'outletStatus' : OutletStatus,
  'outletName' : IDL.Text,
  'walletDue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([Category], [], []),
  'addItemToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addReview' : IDL.Func([IDL.Text, Review], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'addVendor' : IDL.Func([IDL.Principal, Vendor], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([Order], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAnalytics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalProducts' : IDL.Nat,
          'totalOrders' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'totalVendors' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
  'getCustomerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Principal], [IDL.Opt(Vendor)], ['query']),
  'getVendorDashboardStats' : IDL.Func([], [VendorDashboardStats], ['query']),
  'getVendorOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getVendorProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isVendor' : IDL.Func([], [IDL.Bool], ['query']),
  'payCompany' : IDL.Func([], [], []),
  'removeCartItem' : IDL.Func([IDL.Text], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'removeVendor' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
  'updateVendor' : IDL.Func([IDL.Principal, Vendor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'image' : ExternalBlob,
  });
  const Review = IDL.Record({
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
    'reviewer' : IDL.Principal,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'ratings' : IDL.Vec(Review),
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'vendor' : IDL.Principal,
    'discount' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const OutletStatus = IDL.Variant({
    'disabled' : IDL.Null,
    'enabled' : IDL.Null,
  });
  const Vendor = IDL.Record({
    'principal' : IDL.Principal,
    'verified' : IDL.Bool,
    'outletStatus' : OutletStatus,
    'name' : IDL.Text,
    'outletName' : IDL.Text,
    'walletDue' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'productId' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'customer' : IDL.Principal,
    'vendor' : IDL.Principal,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const VendorDashboardStats = IDL.Record({
    'totalSalesAmount' : IDL.Nat,
    'outletStatus' : OutletStatus,
    'outletName' : IDL.Text,
    'walletDue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([Category], [], []),
    'addItemToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addReview' : IDL.Func([IDL.Text, Review], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'addVendor' : IDL.Func([IDL.Principal, Vendor], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([Order], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAnalytics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalProducts' : IDL.Nat,
            'totalOrders' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'totalVendors' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCategory' : IDL.Func([IDL.Text], [Category], ['query']),
    'getCustomerOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Principal], [IDL.Opt(Vendor)], ['query']),
    'getVendorDashboardStats' : IDL.Func([], [VendorDashboardStats], ['query']),
    'getVendorOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getVendorProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isVendor' : IDL.Func([], [IDL.Bool], ['query']),
    'payCompany' : IDL.Func([], [], []),
    'removeCartItem' : IDL.Func([IDL.Text], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'removeVendor' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateCategory' : IDL.Func([IDL.Text, Category], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Text, Product], [], []),
    'updateVendor' : IDL.Func([IDL.Principal, Vendor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };