/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'totalOrders' : bigint,
  'totalCommission' : bigint,
  'totalSales' : bigint,
  'totalVendors' : bigint,
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface Category {
  'id' : string,
  'name' : string,
  'image' : ExternalBlob,
}
export type City = { 'other' : null } |
  { 'unnao' : null } |
  { 'kanpur' : null };
export interface Discount {
  'code' : string,
  'vendor' : [] | [Principal],
  'percentage' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'total' : bigint,
  'customer' : Principal,
  'city' : City,
  'commissionApplied' : boolean,
  'vendor' : Principal,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'processing' : null };
export type OutletStatus = { 'disabled' : null } |
  { 'enabled' : null };
export interface Product {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'ratings' : Array<Review>,
  'description' : string,
  'stock' : bigint,
  'vendor' : Principal,
  'discount' : [] | [bigint],
  'category' : string,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface PublicVendorProfile {
  'principal' : Principal,
  'verified' : boolean,
  'outletStatus' : OutletStatus,
  'area' : string,
  'city' : City,
  'name' : string,
  'storeCategory' : StoreCategory,
  'outletPhoto' : ExternalBlob,
  'outletName' : string,
  'mobile' : string,
}
export interface Review {
  'comment' : string,
  'rating' : bigint,
  'reviewer' : Principal,
}
export type StoreCategory = { 'cosmeticStore' : null } |
  { 'groceryStore' : null } |
  { 'clothStore' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'customer' : null } |
  { 'vendor' : null };
export interface Vendor {
  'gst' : [] | [string],
  'principal' : Principal,
  'verified' : boolean,
  'documents' : Array<ExternalBlob>,
  'outletStatus' : OutletStatus,
  'area' : string,
  'city' : City,
  'name' : string,
  'storeCategory' : StoreCategory,
  'aadhaar' : string,
  'outletPhoto' : ExternalBlob,
  'outletName' : string,
  'mobile' : string,
  'walletDue' : bigint,
}
export interface VendorApplication {
  'gst' : [] | [string],
  'principal' : Principal,
  'documents' : Array<ExternalBlob>,
  'area' : string,
  'city' : City,
  'name' : string,
  'storeCategory' : StoreCategory,
  'aadhaar' : string,
  'outletPhoto' : ExternalBlob,
  'outletName' : string,
  'timestamp' : Time,
  'mobile' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[Category], undefined>,
  'addDiscount' : ActorMethod<[Discount], undefined>,
  'addOrUpdateVendor' : ActorMethod<[Principal, Vendor], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[string, Review], undefined>,
  'addToCart' : ActorMethod<[CartItem], undefined>,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'applyAsVendor' : ActorMethod<[VendorApplication], undefined>,
  'approveVendor' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[Order], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getAnalyticsData' : ActorMethod<[], AnalyticsData>,
  'getCallerRole' : ActorMethod<[], UserRole__1>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerVendor' : ActorMethod<[], [] | [Vendor]>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCustomerOrders' : ActorMethod<[], Array<Order>>,
  'getCustomerProducts' : ActorMethod<[], Array<Product>>,
  'getDiscounts' : ActorMethod<[], Array<Discount>>,
  'getOrdersByCity' : ActorMethod<[City], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getOutletProfile' : ActorMethod<[], Vendor>,
  'getOutletsByCity' : ActorMethod<[City], Array<PublicVendorProfile>>,
  'getOutletsByName' : ActorMethod<[string], Array<PublicVendorProfile>>,
  'getOutletsByStoreCategory' : ActorMethod<
    [StoreCategory],
    Array<PublicVendorProfile>
  >,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorApplications' : ActorMethod<[], Array<VendorApplication>>,
  'getVendorDocuments' : ActorMethod<[Principal], Array<ExternalBlob>>,
  'getVendorOrders' : ActorMethod<[], Array<Order>>,
  'getVendorProducts' : ActorMethod<[], Array<Product>>,
  'getWishlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isVendor' : ActorMethod<[], boolean>,
  'markVendorAsPaid' : ActorMethod<[Principal], undefined>,
  'rejectVendor' : ActorMethod<[Principal], undefined>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setVendorOutletStatus' : ActorMethod<[Principal, OutletStatus], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateOutletProfile' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      ExternalBlob,
      City,
      [] | [string],
      StoreCategory,
    ],
    undefined
  >,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];